# **LAB TASKS:** "Genetic Algorithm"
1. Add functionality to detect diagonal conflicts in the board to evaluate board fitness.
2. Add mutation operation in the above code as a separate function similar to the ones added for crossover, fitness and other operations of Genetic Algorithms above. Generate a random number in the range 0 to 7 to decide about which Queen (Gene) to replace in the chromosome with the randomly generated number in the range (0 to 7) representing column number.
3. Restructure the complete code to take the number of boards (population size) from the user as an input and perform all the operations of Genetic Algorithm.#

In [ ]:
import numpy as np
import random

def create_8_queens_board(): #Create chessboard
    queens_board = np.full((8,8), '.')
    print(queens_board) #Display board with dots

    # Place queens (represented by 'Q') on the board
    for row in range(0,8): #loop for each row
      col = random.randint(0, 7)
      print(row,col)
      queens_board[row, col] = 'Q'

    return queens_board #chessboard with Q display

def board_chromosome(board):
  queens_positions = np.argwhere(board == 'Q')
  print(queens_positions)
  cols = queens_positions[:, 1] # This will returns columns for all rows in a 2D matrix.
  print(cols)

  return cols

def calculate_fitness_numpy(board):
    # Get the positions of the queens
    queens_positions = np.argwhere(board == 'Q')
    num_queens = len(queens_positions)

    # Extract rows and columns
    rows = queens_positions[:, 0]
    cols = queens_positions[:, 1]

    print(rows)
    print('cols',cols)

    # Count attacking pairs
    unique_cols, counts = np.unique(cols, return_counts=True)
    print(unique_cols,counts)
    # Apply check to keep only columns that appear exactly once
    unique_only = unique_cols[counts == 1]
    #row_attacks = num_queens - len(np.unique(rows))  # Count rows with multiple queens
    col_attacks = num_queens - len(unique_only)  # Count columns with multiple queens
    print(col_attacks)


    # Count diagonal attacking pairs
    diagonal_attacks = 0
    for i in range(num_queens):
        for j in range(i + 1, num_queens):
            if abs(rows[i] - rows[j]) == abs(cols[i] - cols[j]):
                diagonal_attacks += 1

    # Total attacking pairs
    total_attacks = col_attacks + diagonal_attacks
    # Fitness is the number of non-attacking queens
    fitness = num_queens - total_attacks
    return fitness

In [ ]:
board1 = create_8_queens_board()
c1=board_chromosome(board1)
fb1=calculate_fitness_numpy(board1)
print(board1)
print('Chromosome',c1)
print('Fitness',fb1)

print('-----------------','\n')

board2 = create_8_queens_board()
c2=board_chromosome(board2)
fb2=calculate_fitness_numpy(board2)
print(board2)
print('Chromosome',c2)
print('Fitness',fb2)

print('-----------------')

board3 = create_8_queens_board()
c3=board_chromosome(board3)
fb3=calculate_fitness_numpy(board3)
print(board3)
print('Chromosome',c3)
print('Fitness',fb3)

print('-----------------')

board4 = create_8_queens_board()
c4=board_chromosome(board4)
fb4=calculate_fitness_numpy(board4)
print(board4)
print('Chromosome',c4)
print('Fitness',fb4)
print('-----------------')

[['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']]
0 5
1 3
2 3
3 4
4 4
5 3
6 0
7 3
[[0 5]
 [1 3]
 [2 3]
 [3 4]
 [4 4]
 [5 3]
 [6 0]
 [7 3]]
[5 3 3 4 4 3 0 3]
[0 1 2 3 4 5 6 7]
cols [5 3 3 4 4 3 0 3]
[0 3 4 5] [1 4 2 1]
6
[['.' '.' '.' '.' '.' 'Q' '.' '.']
 ['.' '.' '.' 'Q' '.' '.' '.' '.']
 ['.' '.' '.' 'Q' '.' '.' '.' '.']
 ['.' '.' '.' '.' 'Q' '.' '.' '.']
 ['.' '.' '.' '.' 'Q' '.' '.' '.']
 ['.' '.' '.' 'Q' '.' '.' '.' '.']
 ['Q' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' 'Q' '.' '.' '.' '.']]
Chromosome [5 3 3 4 4 3 0 3]
Fitness -1
----------------- 

[['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.'

Add mutation operation in the above code as a separate function similar to the ones added for crossover, fitness and other operations of Genetic Algorithms above. Generate a random number in the range 0 to 7 to decide about which Queen (Gene) to replace in the chromosome with the randomly generated number in the range (0 to 7) representing column number.

In [ ]:
def top_two_chromosomes(boards, chromosomes, fitness_values):
    # Combine fitness with corresponding boards and chromosomes
    combined = list(zip(fitness_values, boards, chromosomes))


    # Sort by fitness (ascending, so the smallest fitness comes first)
    sorted_combined = sorted(combined, key=lambda x: x[0])
    #combined.sort(key=lambda x: x[0])
    print('combined',combined)
    print('sorted_combined',sorted_combined)

    # Extract the top two boards and chromosomes based on fitness
    top_two = sorted_combined[-2:]

    return top_two

# Combine all the boards, chromosomes, and fitness values
boards = [board1, board2, board3, board4]
chromosomes = [c1, c2, c3, c4]
fitness_values = [fb1, fb2, fb3, fb4]

# Get the top two chromosomes and boards
top_two = top_two_chromosomes(boards, chromosomes, fitness_values)
print('top_two')
print(top_two)

parent1 = top_two[-1][2]  # Chromosome of the first top board
parent2 = top_two[-2][2]  # Chromosome of the second top board

def mutate_chromosome(chromosome):
        # Randomly select a gene (queen) to mutate
    index_to_mutate = random.randint(0, 7)

    # Generate a new random value (column) for the gene
    new_gene_value = random.randint(0, 7)

    # Replace the old gene with the new one
    chromosome[index_to_mutate] = new_gene_value

    return chromosome

def single_point_crossover(parent1, parent2):
    # Randomly choose a crossover point
    #crossover_point = np.random.randint(1, len(parent1) - 1)
    crossover_point=4
    print('crossoverpoint',crossover_point)

    # Create offspring by combining parts of parents at the crossover point
    offspring1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    offspring2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))

    return offspring1, offspring2

# Example parent chromosomes from your 8-queen boards
#parent1 = np.array([2, 5, 3, 6, 2, 6, 2, 7])  # Fitness 3
#parent2 = np.array([2, 4, 5, 3, 3, 1, 7, 0])  # Fitness 3

# Perform single-point crossover
offspring1, offspring2 = single_point_crossover(parent1, parent2)
# Mutate the offspring
offspring1 = mutate_chromosome(offspring1)
offspring2 = mutate_chromosome(offspring2)

print("Parent 1:", parent1)
print("Parent 2:", parent2)
print("Offspring 1:", offspring1)
print("Offspring 2:", offspring2)

combined [(-1, array([['.', '.', '.', '.', '.', 'Q', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.'],
       ['.', '.', '.', '.', 'Q', '.', '.', '.'],
       ['.', '.', '.', '.', 'Q', '.', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.'],
       ['Q', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.']], dtype='<U1'), array([5, 3, 3, 4, 4, 3, 0, 3])), (-2, array([['.', '.', 'Q', '.', '.', '.', '.', '.'],
       ['Q', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', 'Q', '.', '.'],
       ['.', '.', '.', '.', 'Q', '.', '.', '.'],
       ['.', '.', '.', '.', 'Q', '.', '.', '.'],
       ['.', '.', '.', 'Q', '.', '.', '.', '.'],
       ['Q', '.', '.', '.', '.', '.', '.', '.']], dtype='<U1'), array([2, 0, 3, 5, 4, 4, 3, 0])), (-1, array([['.', '.', '.', '.', 'Q', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', 'Q', '

# **Restructure the complete code to take the number of boards (population size) from the user as an input and perform all the operations of Genetic Algorithm.**

In [ ]:
import numpy as np
import random

def create_8_queens_board():
    #Creates a random 8x8 chessboard with 8 queens placed randomly.
    board = np.full((8, 8), '.')
    for row in range(8):
        col = random.randint(0, 7)
        board[row, col] = 'Q'
    return board

def board_chromosome(board):
    #Extracts the chromosome (queen positions) from the board.
    queens_positions = np.argwhere(board == 'Q')
    cols = queens_positions[:, 1]
    return cols

def calculate_fitness_numpy(board):
    #Calculates the fitness
    queens_positions = np.argwhere(board == 'Q')
    num_queens = len(queens_positions)
    rows = queens_positions[:, 0]
    cols = queens_positions[:, 1]

    # Calculate column attacks
    unique_cols, counts = np.unique(cols, return_counts=True)
    unique_only = unique_cols[counts == 1]
    col_attacks = num_queens - len(unique_only)

    # Calculate diagonal attacks
    diagonal_attacks = 0
    for i in range(num_queens):
        for j in range(i + 1, num_queens):
            if abs(rows[i] - rows[j]) == abs(cols[i] - cols[j]):
                diagonal_attacks += 1

    total_attacks = col_attacks + diagonal_attacks
    fitness = num_queens - total_attacks  # Fitness is the number of non-attacking queens
    return fitness

def top_two_chromosomes(boards, chromosomes, fitness_values):
    #Selects the top two chromosomes based on fitness.
    combined = list(zip(fitness_values, boards, chromosomes))
    sorted_combined = sorted(combined, key=lambda x: x[0])
    top_two = sorted_combined[-2:]  # Get the two with highest fitness
    return top_two

def mutate_chromosome(chromosome):
    #Mutates a chromosome randomly
    index_to_mutate = random.randint(0, 7)
    new_gene_value = random.randint(0, 7)
    chromosome[index_to_mutate] = new_gene_value
    return chromosome

def single_point_crossover(parent1, parent2):
    #Performs single-point crossover
    crossover_point = 4  # You can make this random if needed
    offspring1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    offspring2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return offspring1, offspring2

# Get population size from user
population_size = int(input("Enter the population size: "))

# Create initial population
boards = [create_8_queens_board() for _ in range(population_size)]
chromosomes = [board_chromosome(board) for board in boards]
fitness_values = [calculate_fitness_numpy(board) for board in boards]

    # Genetic Algorithm loop
for generation in range(5):  # Run for 100 generations (example)
    # Selection
    top_two = top_two_chromosomes(boards, chromosomes, fitness_values)
    parent1 = top_two[-1][2]
    parent2 = top_two[-2][2]

    # Crossover and Mutation
    offspring1, offspring2 = single_point_crossover(parent1, parent2)
    offspring1 = mutate_chromosome(offspring1)
    offspring2 = mutate_chromosome(offspring2)

    # Replace least fit individuals with offspring (example replacement strategy)
    # You might need a more sophisticated replacement strategy here
    boards[-2:] = [create_8_queens_board(),create_8_queens_board()] # Replace with the list of the boards
    chromosomes[-2:] = [offspring1, offspring2] # Replace with chromosomes
    fitness_values[-2:] = [calculate_fitness_numpy(boards[-2]), calculate_fitness_numpy(boards[-1])]  #Recalculate the fitness

    print(f"Generation {generation + 1}:")
    for i in range(population_size):
        print(f"Chromosome {i + 1}: {chromosomes[i]}, Fitness: {fitness_values[i]}")

    print("-" * 5)  # Separator between generations

Enter the population size: 2
Generation 1:
Chromosome 1: [6 6 6 5 0 1 7 1], Fitness: 1
Chromosome 2: [3 4 4 0 0 2 4 1], Fitness: -4
-----
Generation 2:
Chromosome 1: [6 6 6 5 0 6 4 1], Fitness: 0
Chromosome 2: [3 4 4 0 0 1 7 7], Fitness: -5
-----
Generation 3:
Chromosome 1: [6 6 6 5 0 5 7 7], Fitness: -1
Chromosome 2: [3 4 4 0 0 6 4 5], Fitness: -2
-----
Generation 4:
Chromosome 1: [6 6 6 5 0 6 4 5], Fitness: -2
Chromosome 2: [3 4 5 0 0 5 7 7], Fitness: 0
-----
Generation 5:
Chromosome 1: [3 4 5 0 0 6 4 5], Fitness: -5
Chromosome 2: [6 0 6 5 0 5 7 7], Fitness: 2
-----
